### PR TITLE
Fix project badging table

### PR DESCRIPTION
**Pull request by Teek-tech**
- Consumed project-badging-api into project table
- Fix issues with project-badge-svg (format markup url)
- Redesign project table to align with UI
- Add search and dropdown filter to table

Note: I still can't find project title on data retrieved via the api.
cc: @kaxada

### CODE REVIEW

**Comment by kaxada** [comment]
@Teek-tech let me sort out the project title for you

**Comment by Teek-tech** [comment]
Alright, @kaxada 
Looking forward to it.

**Review by kaxada — COMMENTED** [review]
@Teek-tech I added the title and removed the random string URL since it doesn't give a good UX. I would want to see how longer URLS affect the table layout in future but for now I think they can work

**Comment by Teek-tech** [comment]
@kaxada, Thank you.
Can I see the payload from your end?
Nothing has changed from my end.

**Pull request merged**
