### PR TITLE
fix breaking changes

### PR DESCRIPTION
**Pull request by Teek-tech**

### CODE REVIEW

**Review by misspee007 — COMMENTED** [review]
Hey @Teek-tech, how about this part?

image

**Comment by Teek-tech** [comment]
> Hey @Teek-tech, how about this part?
> 
> image

Those part are supposed to touch the extreme part of the parent container but then it forms a line on bigger screen and it doesn’t look good. @kaxada suggested we do it the way it is now.
@iamkingsleey what do you think?

**Comment by Teek-tech** [comment]
@misspee007 kindly go ahead and merge it so it doesn’t cause more problem for new pull requests.
You can also go ahead and fix the project page responsiveness when you’re done.

**Comment by misspee007** [comment]
> > Hey @Teek-tech, how about this part?
> > image
> 
> Those part are supposed to touch the extreme part of the parent container but then it forms a line on bigger screen and it doesn’t look good. @kaxada suggested we do it the way it is now. @iamkingsleey what do you think?

The screenshot is not from a big screen.

**Comment by misspee007** [comment]
> @misspee007 kindly go ahead and merge it so it doesn’t cause more problem for new pull requests. You can also go ahead and fix the project page responsiveness when you’re done.

Did you mean the "About DEI Badging" page?

**Pull request merged**
